trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/install-dependencies.yaml

  # Kör en hel testfil (Kim_Tests.robot)
  - script: |
      robot --output results/logs/output_kim_tests.xml --log results/logs/log_kim_tests.html --report results/logs/report_kim_tests.html tests/kim_tests.robot
    displayName: 'Run Test File "Kim Tests"'

  # Kör ett specifikt testfall från Kim_Tests.robot
  - script: |
      robot --test "user successfully buys VIP-Tickets for the whole family" --output results/logs/output_kim_family_tickets.xml --log results/logs/log_kim_family_tickets.html --report results/logs/report_kim_family_tickets.html tests/kim_tests.robot
    displayName: 'Run Specific Test Case "user successfully buys VIP-Tickets for the whole family" (kim tests)'

  # Publicera testrapporter
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-develop'
    displayName: 'Publish Robot Framework Reports'